var totalMangoes = 17;
var totalPerson = 5;
//  (/) this / signs means the output will show only vagfol.....
//  (%) this % signs means the output will show only vagsesh.....

// vagfol output hisebe dekhaite chaile ei vabe korte hobe............
var remainder = totalMangoes / totalPerson;
console.log(remainder);

// vagsesh output hisebe dekhaite chaile ei vabe korte hobe.......
var remainder = totalMangoes % totalPerson;
console.log(remainder);
