// variable declaration.......................
var tomatoPrice = 25;
// variable value update .....................................
tomatoPrice = 30;

// add something to the previous value.....................................
var price1 = 25;
var price2 = 15;
// add something with the existing value.....................................
price1 = price1 + 12;
console.log(price1);

// addition to the same variables.................................
// += means adding some value to the existing value (advance level)................
price1 += 10; 
console.log(price1)

// deducting something to the same variables..............................
price2 = price2 - 5;
console.log(price2)
// shorthand -= means deducting something to the same variables (advance level)..............
price2 -= 5;
console.log(price2) 

// in same way we can do multiple as well as division........................

// another method of adding and deducting only 1 with the existing value............ 
// adding 1 with the existing value...................
var age = 24;
age = age + 1;
console.log(age)
// ++ means adding 1 with existing value...........
age++;

// deducting 1 with the existing value...................
var love = 100;
love = love - 1
console.log(love)
// -- means deducting 1 with the existing value...................
love--; 
console.log(love)